version: "3.9"

services:
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rosatom-be
    volumes:
      - ./database/data:/var/lib/postgresql/data